let TWITCH_CLIENT_ID = 'tqd0h5qcgtgyx26su37d910qwu3bky'
let KEY_TWITCH_TOKEN = 'twitchToken'
let KEY_FOLLOWER_LOGIN_ID = 'followerLoginId'
let KEY_FOLLOWER_ID = 'followerId'
let KEY_LIVE_STREAM = 'liveStream'
let KEY_UPDATE_TS = 'updatedAt'
let EVENT_UPDATE_LIVE_STREAM = 'updateLiveStream'
let EVENT_REFRESHED = 'refreshed'
