// credentials
let TWITCH_CLIENT_ID = 's1rfeomm030qieexrb8yuxa5z4ae2m'

// storage key
let KEY_TWITCH_TOKEN = 'KEY_TWITCH_TOKEN'
let KEY_FOLLOWER_LOGIN_ID = 'KEY_FOLLOWER_LOGIN_ID'
let KEY_FOLLOWER_ID = 'KEY_FOLLOWER_ID'
let KEY_LIVE_STREAM = 'KEY_LIVE_STREAM'
let KEY_UPDATE_TS = 'KEY_UPDATE_TS'
let KEY_NOTIFICATION = 'KEY_NOTIFICATION'

// event name
let EVENT_UPDATE_LIVE_STREAM = 'EVENT_UPDATE_LIVE_STREAM'
let EVENT_REFRESHED = 'EVENT_REFRESHED'
