// configs
const REFRESH_INTERVAL_MIN = 2; // in minutes

// credentials
const TWITCH_CLIENT_ID = 's1rfeomm030qieexrb8yuxa5z4ae2m';

// storage key
const KEY_TWITCH_TOKEN = 'KEY_TWITCH_TOKEN';
const KEY_FOLLOWER_LOGIN_ID = 'KEY_FOLLOWER_LOGIN_ID';
const KEY_FOLLOWER_ID = 'KEY_FOLLOWER_ID';
const KEY_LIVE_STREAM = 'KEY_LIVE_STREAM';
const KEY_UPDATE_TS = 'KEY_UPDATE_TS';
const KEY_NOTIFICATION = 'KEY_NOTIFICATION';
const KEY_DARK_MODE = 'KEY_DARK_MODE';

// event name
const EVENT_UPDATE_LIVE_STREAM = 'EVENT_UPDATE_LIVE_STREAM';
const EVENT_REFRESHED = 'EVENT_REFRESHED';
